#!/bin/sh
#
#	Device Input Controller Test
#
#	  Remark: This examination premises that Weston does not run.

# 1 Delete log file
mkdir ../tests/testlog 2> /dev/null
rm -fr ../tests/testlog/* 2> /dev/null

# 2 set weston environment
export XDG_RUNTIME_DIR=/run/user/5000

# 3 Start Device Input Controllers
export DIC_GTFORCE_CONF="../settings/g27racingwheel.conf"
../gtforce/ico_uxf_dic-gtforce -d -L 2> ../tests/testlog/gtforce.log &
sleep 0.5

# 4 Start Weston
/usr/bin/weston --idle-time=0 $WESTON_BACKEND --log=../tests/testlog/weston.log &
sleep 600

# 5 End of Test
sleep 1
/usr/bin/killall weston
/usr/bin/killall ico_uxf_dic-gtforce
sleep 1

# 9 Check Error
FOUND_ERR=0
/bin/grep "ERR>" testlog/*
if [ "$?" != "1" ] ; then
	FOUND_ERR=1
fi
/bin/grep "WRN>" testlog/*
if [ "$?" != "1" ] ; then
	FOUND_ERR=1
fi
/bin/grep "Error" testlog/*
if [ "$?" != "1" ] ; then
	FOUND_ERR=1
fi
/bin/grep "error" testlog/*
if [ "$?" != "1" ] ; then
	FOUND_ERR=1
fi
/bin/grep "Fail" testlog/*
if [ "$?" != "1" ] ; then
	FOUND_ERR=1
fi

if [ $FOUND_ERR = 0 ] ; then
	echo "Device Input Controller Test: OK"
else
	echo "Device Input Controller Test: ERROR"
fi

